name: Update Local Repository

on:
  push:
    branches:
      - test  # Change this to your branch name if needed

jobs:
  update-local:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: test  # Change this to your branch name if needed

      - name: Pull Changes to Local Repository
        run: |
          cd "C:\Users\Kamil\Local Sites\complete-interior\app\public\wp-content\themes\webcraft-theme"
          git fetch origin
          git reset --hard origin/test  # Change this to your branch name if needed
        shell: powershell
